services:
  database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=rs-workshop
      - POSTGRES_PASSWORD=rs-workshop
      - POSTGRES_DB=rs-workshop
    ports:
      - 5432:5432
    volumes:
      - rs-workshop:/var/lib/postgresql/data

volumes:
  rs-workshop:
